"""Add sort_value index"""

# revision identifiers, used by Alembic.
revision = '526277918626'
down_revision = 'aca3b384e03a'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dataset_sort_value'), 'dataset', ['sort_value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dataset_sort_value'), table_name='dataset')
    # ### end Alembic commands ###
